# Example usage

To use `regressors_grano` in a project:

In [ ]:
from sklearn.datasets import load_diabetes
import numpy as np
import os
from regressors_grano import OrdinaryLeastSquaresRegressor
from regressors_grano import GradBoostRegressor
from regressors_grano import RidgeRegressionRegressor
from regressors_grano import KNeigRegressor
from regressors_grano import LassoRegressor
from regressors_grano import EnsembleRegressor

In [ ]:
# show working directory
os.getcwd()

'c:\\Users\\grano\\Nextcloud\\FH Kufstein\\02_Studienunterlagen\\Semester_2_SS_2024\\Softwareentwicklung 2\\project\\softwareentwicklung-2-projekt\\multi_model_ensemble_regressor'

In [ ]:
# load data
data = load_diabetes() # mean centered and scaled by the standard deviation times the square root of n_samples

## Data exploration

In [ ]:
# show feature matrix data shape
data.data.shape     

(442, 10)

In [ ]:
# show target data shape
data.target.shape

(442,)

In [ ]:
# load feature matrix and target data
X = data.data
y = data.target

In [ ]:
# print feature matrix
print(X)

[[ 0.03807591  0.05068012  0.06169621 ... -0.00259226  0.01990749
  -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 ... -0.03949338 -0.06833155
  -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 ... -0.00259226  0.00286131
  -0.02593034]
 ...
 [ 0.04170844  0.05068012 -0.01590626 ... -0.01107952 -0.04688253
   0.01549073]
 [-0.04547248 -0.04464164  0.03906215 ...  0.02655962  0.04452873
  -0.02593034]
 [-0.04547248 -0.04464164 -0.0730303  ... -0.03949338 -0.00422151
   0.00306441]]


In [ ]:
# show data type of feature matrix
type(X)

numpy.ndarray

In [ ]:
# show data type of target data
type(y)

numpy.ndarray

## Inspect single regressor classes

In [ ]:
ls = OrdinaryLeastSquaresRegressor()
ls.fit(X, y)
ls.score(X, y)

Regression model trained.
The r2-score is: 0.5177484222203498


0.5177484222203498

In [ ]:
gb = GradBoostRegressor()
gb.fit(X, y)
gb.score(X, y)

Regression model trained.
The r2-score is: 0.7990392018966864


0.7990392018966864

In [ ]:
rr = RidgeRegressionRegressor()
rr.fit(X, y)
rr.score(X, y)

Regression model trained.
The r2-score is: 0.45123062774361744


0.45123062774361744

In [ ]:
kn = KNeigRegressor()
kn.fit(X, y)
kn.score(X, y)

Regression model trained.
The r2-score is: 0.604957605699507


0.604957605699507

In [ ]:
kn = LassoRegressor()
kn.fit(X, y)
kn.score(X, y)

Regression model trained.
The r2-score is: 0.3573787382316279


0.3573787382316279

## Ensemble regressor analysis

### Preliminary analysis concerning functionality

In [ ]:
regre = EnsembleRegressor(["gb", "kn", "la"])

Gradient Boosting Regressor loaded.
KNeighbors Regressor loaded.
Lasso Regressor loaded.


In [ ]:
print(regre)

The following regressors are included: Gradient Boosting Regressor, KNeighbors Regressor, Lasso Regressor


In [ ]:
del regre[1]

In [ ]:
regressor = LassoRegressor()
regre[0] = regressor

Gradient Boosting Regressor replaced by Lasso Regressor.


In [ ]:
regressor = RidgeRegressionRegressor()

In [ ]:
print(regre)

The following regressors are included: Lasso Regressor, Lasso Regressor


In [ ]:
text_regressor = regre[1]
print(text_regressor.name)

Lasso Regressor returned.
Lasso Regressor


In [ ]:
array_1 = np.array([1, 2])
array_2 = np.array([1, 3])

array_3 = np.column_stack((array_1, array_2))
print(np.mean(array_3, axis=1))

[1.  2.5]


In [ ]:
type(y) == type(array_3)
type(y)

numpy.ndarray

In [ ]:
predictions = kn.predict(X)
type(predictions) == type(array_3)

Regression model predictions provided.


True

### Main analysis concerning functionality

In [ ]:
# instantiate regressor (__getitem__)
ensemble_regre = EnsembleRegressor(["kn", "la", "ls"])

KNeighbors Regressor loaded.
Lasso Regressor loaded.
Ordinary Least Squares Regressor loaded.


In [ ]:
# retrive regressor (__getitem__)
kn_regressor = ensemble_regre[1]

Lasso Regressor returned.


In [ ]:
# change regressor (__setitem__)
rr_regressor = RidgeRegressionRegressor()
ensemble_regre[0] = rr_regressor

KNeighbors Regressor replaced by Ridge Regression Regressor.


In [ ]:
# delete regressor (__delitem__)
del ensemble_regre[2]

In [ ]:
# print regressors (__str__)
print(ensemble_regre)

The following regressors are included: Ridge Regression Regressor, Lasso Regressor


In [ ]:
# fit all regressors (fit)
ensemble_regre.fit(X, y)

Training Ridge Regression Regressor:
Regression model trained.
Training Lasso Regressor:
Regression model trained.


In [ ]:
# retrieve trained regressor and provide predictions
rr_regresssor = ensemble_regre[0]
print(rr_regressor.predict(X)[:3])
rr_regressor.score(X, y)

# retrieve trained regressor and provide predictions
lasso_regresssor = ensemble_regre[1]
print(lasso_regresssor.predict(X)[:3])

Ridge Regression Regressor returned.
Regression model predictions provided.
[182.67335421  90.99860656 166.11347597]
The r2-score is: 0.45123062774361744
Lasso Regressor returned.
Regression model predictions provided.
[181.08083908 112.0212857  169.32280394]


In [ ]:
# eval preds of ensemble regressor (predict)
# retrive ensemble predictions representing the mean of single regressor preds
ensemble_regre.predict(X)[:3]

Ridge Regression Regressor:
Regression model predictions provided.
Lasso Regressor:
Regression model predictions provided.


array([181.87709664, 101.50994613, 167.71813995])

In [ ]:
# train and eval preds of ensemble regressor (fit_predict)
ensemble_regre.fit_predict(X, y)[:3]

Training Ridge Regression Regressor:
Regression model trained.
Training Lasso Regressor:
Regression model trained.
Ridge Regression Regressor:
Regression model predictions provided.
Lasso Regressor:
Regression model predictions provided.


array([181.87709664, 101.50994613, 167.71813995])

In [ ]:
# eval score of ensemble regressor (score)
ensemble_regre.score(X, y)

Ridge Regression Regressor:
Regression model predictions provided.
Lasso Regressor:
Regression model predictions provided.
Ensemble regressor r2_score = 0.4149997876785507


0.4149997876785507